### ISSUE TITLE
Intellect and Strength

### ISSUE THREAD

**Issue by pilate** [rubensayshi/d3-ehp-calculator#18]
"Intellect" converts directly to "Resist All" at a rate of 10:1.
"Strength" converts directly to "Armor" at a rate of 1:1.

**Comment by pilate** [comment]
I assume this is naturally covered by the manual input of resists and armor, sorry.

**Comment by rubensayshi** [comment]
haha, yea you put in armor/resist which already includes it :-)
but I will need these formulas to display item comparison!
