### ISSUE TITLE
Elite reduction modifier

### ISSUE THREAD

**Issue by rubensayshi** [rubensayshi/d3-ehp-calculator#21]
I added it already, but it should show stacking with melee/ranged/magic I think

**Comment by kirk-ningxin-li** [comment]
Does "reduce damage melee" work vs elite melee?

**Comment by rubensayshi** [comment]
I asume it does

**Comment by asilvas** [comment]
Just missing it in the item calculator portion.

**Comment by rubensayshi** [comment]
thanks for reporting it, hadn't even noticed
