### ISSUE TITLE
Web Page Errors

### ISSUE THREAD

**Issue by Aintru** [rubensayshi/d3-ehp-calculator#25]
Failed to load resource http://ajax.cdnjs.com/ajax/libs/json2/20110223/json2.js
Failed to load resource http://ajax.cdnjs.com/ajax/libs/underscore.js/1.3.3/underscore-min.js
Uncaught TypeError: Cannot set property 'LocalStorage' of undefined backbone.localStorage-min.js:4
Uncaught ReferenceError: Backbone is not defined Character.js:1
Uncaught ReferenceError: _ is not defined Barbarian.js:2
Uncaught ReferenceError: _ is not defined DemonHunter.js:2
Uncaught ReferenceError: _ is not defined Monk.js:2
Uncaught ReferenceError: _ is not defined WitchDoctor.js:2
Uncaught ReferenceError: _ is not defined Wizard.js:2
Uncaught ReferenceError: Backbone is not defined Characters.js:1
Uncaught ReferenceError: Backbone is not defined MainView.js:1
Uncaught ReferenceError: Backbone is not defined IntroView.js:1
Uncaught ReferenceError: Backbone is not defined SimulationView.js:1
Uncaught TypeError: Cannot call method 'extend' of undefined InputView.js:1
Uncaught TypeError: undefined is not a function main.js:50
Failed to load resource http://ajax.cdnjs.com/ajax/libs/backbone.js/0.9.2/backbone-min.js

**Comment by rubensayshi** [comment]
Awh, that sucks :(

thanks for reporting it, finaly an error report which clearly states what goes wrong, I'll start moving the libraries to my own host instead of the cdns!

**Comment by rubensayshi** [comment]
no longer using the cdn and haven't heard anyone complain for a while now :-)
