### ISSUE TITLE
All resistance

### ISSUE THREAD

**Issue by rubensayshi** [rubensayshi/d3-ehp-calculator#26]
people want to input all of their seperate resistances

**Comment by rockon8729** [comment]
On the topic of all resist.  Alot of people were going with 10 Armor = 1 All Resist.  So I put into your calc that my current Item had 10 armor and my upgrade had 1 All Resist.  This resulted in the +1 All Resist in being worse than the 10 Armor.  Then number when they became equal was 7.83 Armor = 1 All Resist.  Was just wondering if that sounded about right and people really just didnt know what they were talking about which im sure we will find to be the case as is with most info people put on forums.

**Comment by rubensayshi** [comment]
armor and AR are 10:1 in the damage reduction formula indeed, but that doesn't mean it results in the same EHP all the time ;)

There are a lot of buffs/passives that give +armor or +AR which make the EHP gained different AND the most important: they scale with eachother!

Try the following, make a new barb with no skills on and 10 armor and 1 AR and you'll notice that the +EHP behind armor and AR are the same for 10 armor and 1 AR.
Now if you make your base armor 1000 you'll notice that you will get more EHP from 1 AR then from 10 armor, or visa versa

Now most barbs are using, tough, nerves, warcry imp and enchantress, sitting around 4900 base armor (11040 buffed) and 700 AR (1050 buffed) 
At that point it's fairly balanced _+10 Armor +2652 EHP; +0.11%_ vs _+1 All Resist +2584 EHP; +0.11%_ but you can the slight difference.

If you can choose between 10 armor or 1 AR, then you should always choose in such a way that you get closer to that 10:1 ratio, since that's the point where both give the same EHP !
However if you're already close to that ratio (between 9:1 and 11:1) you should probally just always go for getting the most of combined value :-)

**Comment by rockon8729** [comment]
Ah ok that makes sense that it was taking into account the buffs on my character page.  I'm playing as a TankDocta (yes they exist just expensive to gear but are really fun to play).  Thanks for the calc I have been posting it in our TankDocta forum here: http://us.battle.net/d3/en/forum/topic/5592459114
