### ISSUE TITLE
[Feature Request] Monk: Option Sorting/Restrictions

### ISSUE THREAD

**Issue by ShaneEbersole** [rubensayshi/d3-ehp-calculator#28]
[I know you already have the restrictions on your radar, but wanted to add this to it]

It would be nice if everything were sorted, with restrictions made for one Mantra and one spirit generator.

The spreadsheet I was working on has:

Mantra [Only 1]
- Healing+Resist
- Healing+Life
- Conviction+Redux
- Evasion
- Evasion+Armor
- N/A

Attacks [Only 1; 2/4secs is too short to stack the EHP buffs]
- Deadly+Armor
- Crippling+Redux
- Fist+Dodge
- N/A

Passives [three slots]
- Resolve
- Seize the Initiative
- Guardian's Path
- Sixth Sense [needs to support crit chance]
- One with Everything
- N/A

Checkboxes
- Enchantress
- Earth Ally

**Comment by rubensayshi** [comment]
yea, I specially want to get rid of the weird behavory with having multiple mantras or runes of the same skill.

atm my priority is getting block in, after that I want to take a look at how the code looks and I think this one goes well with the #35 sharedbuffs since that also requires to redo / cleanup the code a lot.

**Comment by ShaneEbersole** [comment]
Sorting/Restrictions (#28)
MIME-Version: 1.0
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: 7bit

How would block work? You'd put in a damage parameter and work out a
TTL or something?

Sent from my Windows Phone

**Comment by rubensayshi** [comment]
There are a couple of other issues in the tracker right now about time to live, effective healing modifier and stuff.

I still hope I can calculate something based on incoming damage and then create some presets (like the bosses, some common packs)
