### ISSUE TITLE
[Feature request] Efficient health per second

### ISSUE THREAD

**Issue by ghost** [rubensayshi/d3-ehp-calculator#29]
Hi,

First of all, i'd like to thank you for your work. I really enjoy what you're doing and i'm using your calculator every day :)

Let's come down to my request: I saw that you're considering including TTL paired with a database of damage monster. It would be great if you're able to do so but meanwhile, I was thinking of something simpler regarding Life Leach, Potion and all different kind of healing in D3.

Typically, we have some passive that gave us fixed amount of heal per second, or even the life on hit. Thus I was wondering if you could include those capacity to get a new stat : Efficient health per second. It could include the heal per second, the life on hit considering your attack speed and the spell you are using (may have multiple spell at the same time like for the wizard with hydra + blizzard + arcane missile), and also the life leach which will depend on our actual dps.

I imagine something like that: The calculator bases its calcul on a fight with only one monster (if you can do calculus for multiple target, it's even better :D). The user can choose different spell that are assumed to be effective at the same time (like the hydra/blizzard/arcane missile mentioned earlier) and based the calcul of the DPS and so the life leach and life per hit based on the spell active at the same time.

It would not be completely accurate since we still need to launch our spell but it would give a good approximation.

Finally, i think it would not be a waste of time since lot of those calcul would be reused in the calcul of the TTL if you manage to get a hand on a data base of monster's damage.

Thanks for reading this post and thanks again for your work.

Gimlinus

P.S. : I hope my english is not too crapy

**Comment by mayainverse** [comment]
I agree. but i think it would be easier to just show total damage mitigated as it is the same thing as effective healing pretty much.

ehp is HP/DR would be nice if could show the DR on the site so people would know if its an actual upgrade for sustained damage or not. ehp is only good for 2 barb heals and to avoid being bursted to death. high DR is needed for all other ways of healing pots/regen/LoH.

**Comment by ghost** [comment]
I agree that EHP is pretty much the same thing as DR. However, EHP is much more comprehensible. A difference of 0.1% of DR could result of a much more representative difference for EHP. Furthermore, some healing process are not very clear to the common player. For example, i've just been aware about the 80% reduction of life leech in inferno and i still have some difficulties to make a comparison with life/s or life/hit.

Lastly, i often have to chose between better mitigation/less healing and less mitigation/more healing for the itemization. I think it would be very pleasant to be able to compare them on a same level (almost same level) to help us make our choice.

I'm a wizard but i play in HC and will start inferno very soon :D

**Comment by rubensayshi** [comment]
#16 and #13 describe adding some sort of time to live, which would have to be based on x amount of hits of x damage per second or something and we could add life regen to that.

I agree that once you get past the point of getting killed within a few seconds that DR could be more important to focus on then EHP since more EHP won't prevent you from slowly dieing while more DR will :-)

**Comment by rubensayshi** [comment]
closing this issue since #39 (effective healing multiplier) gives a good estimation of this and #13 and #16 are the final implementations I want for this.

Thanks for the feedback so far and I hope you'll see a nice addition soon :D
