### ISSUE TITLE
App is unusably broken on Opera

### ISSUE THREAD

**Issue by listen2** [rubensayshi/d3-ehp-calculator#30]
Might be related to this: http://validator.w3.org/check?uri=http%3A%2F%2Frubensayshi.github.com%2Fd3-ehp-calculator

**Comment by rubensayshi** [comment]
nah it's not related to the invalid html, but I have to admit I never tested opera.
I will install opera later today and see if I can fix it :-)

**Comment by rubensayshi** [comment]
it seems to be working for me with latest opera version, it might be a version problem of the app, could you try hitting CTRL+F5 to do a hard refresh so it fetches new files :) ?

**Comment by ghost** [comment]
I don't know if you tested the app with Safari but i don't detect any issue.

**Comment by listen2** [comment]
Sorry for this late response. I have since upgraded to Opera 12 and everything seems to be working correctly.

**Comment by rubensayshi** [comment]
okay, should problems arise again just let me know and I'll dig into it to fix it :D
