### ISSUE TITLE
EHP - add intro / explaination text

### ISSUE THREAD

**Issue by mitchiru** [rubensayshi/d3-ehp-calculator#40]
What is EHP

Estimated Health Points?
Extra Heat Paddle?

**Comment by rubensayshi** [comment]
hmm are you trolling me as a hint to sugest I should be adding an explanation to the tool or really want to know :D ?

cool movie explaining it by Zravex: http://www.youtube.com/watch?v=9vBWweBQSBY
text with formula: http://www.clicktoloot.com/p/combat.html#effectivehitpoints

**Comment by rubensayshi** [comment]
I should add some info to the first page I guess :D

**Comment by mitchiru** [comment]
I still didn't get the meaning of the abbreviation, but I guess I got what it stands for.

**Comment by rubensayshi** [comment]
Effective Hit Points or effectively how much hit points (health) you can loose before you die
