### ISSUE TITLE
Buffed armour - Force armor (wizard)

### ISSUE THREAD

**Issue by APlusDesign** [rubensayshi/d3-ehp-calculator#44]
When entering my base armor of 3038 into the calculator, it shows in buffed armour as 4708, calculated from 60% increase. 

Force armor is 65%, so my buffed armor should be 5232, based off 65% increase.

I downloaded the code to see if it was incorrect value being applied, but found the multiplier to be correct at 0.65 in model/wizard.js

Why does it calculate the armor buff incorrectly at 60%

?

**Comment by APlusDesign** [comment]
Sorry should mention also, glass cannon is selected, so I understand why the armor buff is lower then expected, but the debuff is 10% so it is not calculating correctly with glass cannon and force armor selected.

Example

## Base armor (3038) - Force armor + glass canon

= (3038 + (3038 \* 0.65)) - ( 3038 \* 0.10)) 
= (3038 + 1974.7) - 303.8
= 5012 - 303.8
= 4708.9

This is correct in your calculations

But in game it shows - 5232 as the buffed armor, so I'm not sure if it is a game bug or not, because your calculations seem to be correct, how-ever it differs from what the game is displaying. I have no other armour buffs.

I tried different combination of applying the buff and debuff, but could not get it to equal 5232...

**Comment by rubensayshi** [comment]
did you consider the enchantress 15% armor buff?
I think she's the difference you're looking for ;)

**Comment by APlusDesign** [comment]
I do not have the followers when looking at those numbers, I made sure to check everything before posting. No follower, no gear buffs.

As stated there seems to be no issue with your calc, apart from displaying a differing number to in game armor, thought it would be worth looking into.

**Comment by rubensayshi** [comment]
I don't have a sorc wih force armor xD so I need to get my brothers account to test it, will do that sometime this week :)
