### ISSUE TITLE
Items from initial character transfer to new character.

### ISSUE THREAD

**Issue by Solipcyst** [rubensayshi/d3-ehp-calculator#45]
Create initial character and add item information.  Then, leave site and come back later.  Then, create a new character and items from the initial character are filled in for the new character.  Furthermore, the item information is now blank for the initial character.

**Comment by rubensayshi** [comment]
Hmm I can't recreate your situation, can you give me some more detail?

-) can you test it once more to see if it still happens?
-) which browser are you using?
-) when you come back, is your old character still there?

**Comment by Solipcyst** [comment]
1.  I'll try to re-create the issue later today.
2.  I was/am using the Steam overlay web browser.  I know that this used to
   essentially be a wrapper for Internet Explorer, but I believe it is
   entirely self-contained since they switched over to the WebKit engine in
   order to be cross-platform compatible with Mac OSX.
3.  Yes.

I should note that after the initial hiccup, I zeroed out the items from
the new character and re-created them on my initial character and have not
since seen the items get switched over to the new character again.  As I
said in point 1, though, I'll try making a new character again to see if
the items get shifted over to it later today and get back to you then.

Btw, great tool.  Throw in a DPS calculator and it'll be a fantastic little
one-stop-shop!

On Wed, Jun 27, 2012 at 3:02 AM, Ruben de Vries <
reply@reply.github.com

**Comment by rubensayshi** [comment]
closing this since it seems to have been some edge case scenario
