### ISSUE TITLE
Feature Request: Block+Dodge EHP

### ISSUE THREAD

**Issue by zr0iq** [rubensayshi/d3-ehp-calculator#47]
Hi,

how about adding block to the EHP? How can it be done? Here is the math.

Let d be the dodge chance, and b be the block chance and r be the real block chance.

The chance to really block is

r = b - d*b

if you dodge the damage anyways, then you do not need to block anymore, even if you do, but it is useless (that it is why -d*b).

How much damage can be avoided by that, in average (block min + block max)/2, so you get:
dodge + block ehp = (r \* (block min + block max) / (2\* total life) + 1) \* dodge ehp

**Comment by rubensayshi** [comment]
hmm, in #33 we were already discussing this, but the amount of EHP you get from a block depends on how hard the mob hits (read this: https://github.com/rubensayshi/d3-ehp-calculator/issues/33#issuecomment-6296691) 

so I need to add something like 'mobs hit you for x hard'

**Comment by zr0iq** [comment]
why would you need something like this?

Estimating a lower limit for the EHP is frankly quite impossible without knowing how hard mobs can hit at max, given even if they have the same dps in one difficulty grade, they have a varying attack speed in that difficulty grade, making it impossible to streamline. You could datamine all the data, but that would be wasted work. Wait for the next nerf ;-)

imho it is only possible without putting to much work in it to give the lowest upper limit of EHP, like described above.

the last formula is somehow really off... I have to think about that some more as the value of r should be modified by the number of attacks :-/ that is the same as with which how hard monsters hit :-(

**Comment by rubensayshi** [comment]
That's what I mean, you block an x amount of attacks until you die, the more times you blocked, the more EHP the shield has given you.

**Comment by zr0iq** [comment]
You could always assume all damage is blocked. and go like:

EHP/( (d-1) \* (b-1) )

or probably add a percentage of what is blocked; like 25-100% blocked.

**Comment by rubensayshi** [comment]
check comment on #33: https://github.com/rubensayshi/d3-ehp-calculator/issues/33#issuecomment-6623940
some1 from diablofans posted a nice formula which I can run with, closing this issue btw, let's continue discussing on #33
