### ISSUE TITLE
Mismatching EHP/Statpoint from buffed to unbuffed

### ISSUE THREAD

**Issue by ghost** [rubensayshi/d3-ehp-calculator#49]
Hey guys,
think i found an issue here.
So, my wizard has unbuffed armor of 3741 and resistance of 450. In the alternative column is see, that for me at the moment its better to stack armor instead of resistance(+210 vs +151).
The problem here is with buffs i get armor of 5773 and resistance of 405 cause of Force Armor and Glass Cannon.
But looking at these buffed stats, i see that resistance is much lower than the 1:10 ratio and i think i must stack more resistance to effective increase my EHP, correct?
Your calculator tells me to stack armor but what i really need is resistance.
regards
jume

**Comment by rubensayshi** [comment]
you're correct that you should normally try to balance armor and resist 10:1, but if you put on energy armor without prismatic rune then the +65% armor makes armor so much better then resist that it puts it at about 1:21

Now if you put on prismatic rune then it's 13:1 ;)
