### ISSUE TITLE
Armor Calculations

### ISSUE THREAD

**Issue by Torlen3** [rubensayshi/d3-ehp-calculator#54]
They are way way off.  It's telling me that my buffed armor is almost 6k more than I have which is way over inflating my ehp.  Pretty much rendering this entire tool useless to me.  Barbarian by the way.

**Comment by rubensayshi** [comment]
hey mate, 

could you try it once more, 

1) making a new character
2) input your stats from character screen ingame, ensure you also enable the checkboxes for the spells and passives (and enchantress if she's with you) on
3) then at the next step it should have reduced your base armor which you input a bit to match the skills and at the bottom show buffed armor

if it's still off, could you give me your armor from character screen, which skills / passives are on and the numbers that show as base stats on the last screen so I can test it ;) ?

**Comment by rubensayshi** [comment]
sorry for slow response btw, was on vacation for a few days ;)
