### ISSUE TITLE
damage reduction elite/magic

### ISSUE THREAD

**Issue by mayainverse** [rubensayshi/d3-ehp-calculator#55]
shouldnt there be a section for champion affixes since they are elite mobs and most are magic damage at least the most dangerous types of damage in the game are from stuff arcane/molten/mortar and the such.

or does that not count like that in the game. same with champions who melee attack or ranged attack wouldnt you get more bonus from having each?

**Comment by rubensayshi** [comment]
Correct, but it's hard to cramp all that information into the interface.
I did redo some of the code which should allow me to implement your
suggestion and I could put the information in a separate tab so it won't be
to crowded!
On Jul 8, 2012 8:17 AM, "mayainverse" <
reply@reply.github.com>
wrote:
