### ISSUE TITLE
Armor/resistance miscalculation?

### ISSUE THREAD

**Issue by Xarst** [rubensayshi/d3-ehp-calculator#57]
Hey there,

while entering my stats, i noticed that the armor and resistance dmg reduction didn´t fit with these ingame. I tried it with some more values and it allways seems to be ~1% of. I doublechecked my entrys and made sure that i dont have buffs nor a companion with me. I made a screen of both(tool vs. ingame) to compare.

http://www.imgload.info/files/arx1344402722r.png

Im sorry that the tooltips are in german but im sure you´ll see what i mean.

**Comment by rubensayshi** [comment]
the ingame tooltips are against mobs of the same level as your character, 60, while in my calculator you can configure the mob level and it's default 63, giving you a bit less reduction :)
