### ISSUE TITLE
Heavenly Body rune inaccurate

### ISSUE THREAD

**Issue by bigword** [rubensayshi/d3-ehp-calculator#58]
Hey, I noticed a small inaccuracy in the way the Monk rune "Heavenly Body" (to the skill Mantra of Healing) is applied.

I THINK the calculator treats it as +% Life but it is actually +% VITALITY. This means it stacks multiplicatively with +% Life.

Example: My monk has unbuffed vitality of 652, +25% life and is level 60. Calculator accurately predicts 28870 Life, unbuffed. BUT after the Mantra, it predicts only a 10% increase to 31179.6 where it should predict an increase of 65.2 VITALITY (bringing my vit to 717.2). This bonus vitality awards 2854.5 life (2282 for 35 per vit, which is modified by my +25% life), which brings me, in game, to 31722.

So, its a small inaccuracy, but i guess it could be larger if someone had more +% life and that could make it better than another option.

**Comment by rubensayshi** [comment]
thanks for reporting this, could you verify if your HP matches now :D ?

**Comment by bigword** [comment]
Hello,

Sorry to say that it does not match still. Is it possible that I need to
clear my cache or something?

Calculator still predicts 31179.6 whereas actual in game is 31722

Thanks
Chris

**Comment by rubensayshi** [comment]
yea, it works correctly for me with your numbers entered, try hitting CTRL+F5, for most browsers that should fetch the website without cache :D
