### ISSUE TITLE
Items associated with newly created character

### ISSUE THREAD

**Issue by tmitchell** [rubensayshi/d3-ehp-calculator#59]
I had one character (Barbarian) populated with several of their items.  I then added a new character (Witch Doctor).

When I go to the items tab on the Witch Doctor, all of their items are set to the ones from the existing Barbarian.  The existing Barbarian has all of his items reset back to "My Item" with no stats.

Browser: Firefox 15.0

**Comment by rubensayshi** [comment]
Yea some stuff was a bit wrong / badly coded as a result of the insane amount of iterations and the result was sharing the items somehow a bit weird ...

I changed it to it should now work properly and all characters should initially grab the items you already had (which were shared :P)
