### ISSUE TITLE
Import from Diablo3 API

### ISSUE THREAD

**Issue by ghost** [rubensayshi/d3-ehp-calculator#60]
Hey, just wanted to inform you, that the API was released.
Availabe here: http://blizzard.github.com/d3-api-docs/#overview

Regards,
jume

**Comment by rubensayshi** [comment]
Hey, tbh I haven't played d3 in months (I actually continued development of this tool like 1.5 months longer then I played d3) and I'm sorry to say that I don't intend to add API support anymore :(

Maybe somebody else might pick it up and add it (I'll merge his code into the live version for sure)

Sorry :(
